// App-level aliases appended after the official Supabase-generated schema.
// Keep this separate: `scripts/generate-types.sh` replaces database.types.ts.

export type PhotoVisibility = "parish" | "house" | "none";
export type UserRole = "member" | "house_leader" | "discipler" | "pastor" | "admin";
export type Gender = "male" | "female";
export type DmWho = "all_parish" | "house" | "discipler" | "none";
export type MembershipStatus = "pending" | "active" | "rejected" | "suspended";
export type ContentStatus = "draft" | "scheduled" | "published";
export type AssetKind = "image" | "audio";
export type Testament = "OT" | "NT";
export type PlanDifficulty = "starter" | "intermediate" | "deep";
export type GivingInterval = "weekly" | "monthly" | "quarterly" | "annually";
export type GivingRecurringStatus = "pending" | "active" | "paused" | "attention" | "cancelled";
export type DonationKind = "one_time" | "recurring";
export type DonationStatus = "pending" | "success" | "failed" | "abandoned" | "reversed";
export type LibraryItemKind = "book" | "manual" | "audio" | "video";
export type HighlightColor = "copper" | "gold" | "sage" | "oxblood" | "blue";
export type ChatKind = "house_group" | "announcements" | "ask_pastor_thread" | "discipler" | "dm" | "parish_group" | "circle";
export type ChatMemberRole = "member" | "leader" | "pastor" | "discipler" | "owner" | "admin";
export type MessageKind = "text" | "voice" | "image" | "system" | "daily_prompt";
export type ReactionEmoji = "🙏" | "❤️" | "amen" | "🔥" | "✋";
export type AskPrivacy = "public" | "private";
export type AskStatus = "awaiting" | "answered";
export type ReportTargetType = "message" | "user" | "prayer_request" | "ask_question";
export type ReportStatus = "open" | "reviewing" | "resolved" | "dismissed";
export type ModerationSeverity = "low" | "medium" | "high";
export type ModerationAction = "logged" | "soft_deleted" | "escalated";
export type NotificationType = "message" | "announcement" | "devotional" | "ask_answered" | "mention" | "daily_prompt" | "streak" | "prayer" | "system";
export type NotificationChannel = "push" | "in_app";
export type PushPlatform = "ios" | "android";
export type VerseImageTheme = "minimal" | "organic" | "bold";
export type VerseImageAspect = "square" | "story";
export type AnnouncementBanner = "event" | "urgent";

export type Parish = Tables<"parishes">;
export type House = Tables<"houses">;
export type Campus = Tables<"campuses">;
export type UserProfile = Tables<"user_profiles">;
export type UserPrivacy = Tables<"user_privacy">;
export type DevotionalSeries = Tables<"devotional_series">;
export type Devotional = Tables<"devotionals">;
export type DevotionalBookmark = Tables<"devotional_bookmarks">;
export type WordOfDay = Tables<"word_of_day">;
export type WordNote = Tables<"word_notes">;
export type ContentAsset = Tables<"content_assets">;
export type BibleVersion = Tables<"bible_versions">;
export type BibleBook = Tables<"bible_books">;
export type BibleChapter = Tables<"bible_chapters">;
export type BibleVerse = Tables<"bible_verses">;
export type Bookmark = Tables<"bookmarks">;
export type Highlight = Tables<"highlights">;
export type Note = Tables<"notes">;
export type ReadingPosition = Tables<"reading_position">;
export type Streak = Tables<"streaks">;
export type EngagementEvent = Tables<"engagement_events">;
export type Chat = Tables<"chats">;
export type ChatMember = Tables<"chat_members">;
export type Message = Tables<"messages">;
export type MessageReaction = Tables<"message_reactions">;
export type PinnedMessage = Tables<"pinned_messages">;
export type PrayerRequest = Tables<"prayer_requests">;
export type PrayerPray = Tables<"prayer_pray">;
export type PrayerReaction = Tables<"prayer_reactions">;
export type AskQuestion = Tables<"ask_questions">;
export type PublicQa = Database["public"]["Views"]["public_qa"]["Row"];
export type Block = Tables<"blocks">;
export type Report = Tables<"reports">;
export type ModerationLog = Tables<"moderation_log">;
export type PushToken = Tables<"push_tokens">;
export type Notification = Tables<"notifications">;
export type NotificationPreference = Tables<"notification_preferences">;
export type VerseImage = Tables<"verse_images">;
export type Announcement = Tables<"announcements">;
export type ReadingPlan = Tables<"reading_plans">;
export type ReadingPlanDay = Tables<"reading_plan_days">;
export type ReadingPlanSubscription = Tables<"reading_plan_subscriptions">;
export type ReadingPlanProgress = Tables<"reading_plan_progress">;
export type GivingFund = Tables<"giving_funds">;
export type GivingRecurring = Tables<"giving_recurring">;
export type Donation = Tables<"donations">;
export type LibraryItem = Tables<"library_items">;
export type MemberDeletion = Tables<"member_deletions">;
export type FormationActivity = Tables<"formation_activities">;
export type ScriptureCollection = Tables<"scripture_collections">;
export type ScriptureCollectionVerse = Tables<"scripture_collection_verses">;
export type FormationCampaign = Tables<"formation_campaigns">;
export type FormationCampaignCompletion = Tables<"formation_campaign_completions">;
export type FellowshipEvent = Tables<"fellowship_events">;
export type FellowshipEventRsvp = Tables<"fellowship_event_rsvps">;
export type CircleMeeting = Tables<"circle_meetings">;
export type CircleRecording = Tables<"circle_recordings">;

export type ChapterVerse = { number: number; text: string };
export type ChapterPayload = {
  version: string;
  book: string;
  abbrev: string;
  chapter: number;
  reference: string;
  verse_count: number;
  verses: ChapterVerse[];
} | null;

export type SearchResult = {
  verse_id: string;
  reference: string;
  book_name: string;
  chapter: number;
  verse: number;
  text: string;
  rank: number;
};
